# Generated by Django 6.0.6 on 2026-09-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('asset_admin', 'Asset Admin'), ('asset_user', 'Asset User'), ('manager', 'Manager')], default='asset_user', max_length=50),
        ),
    ]
