# Generated by Django 5.2.5 on 2025-12-29 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('asset_type', models.CharField(choices=[('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Printer', 'Printer'), ('Phone', 'phone'), ('cell', 'cell')], default='Laptop', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('series_number', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('In Use', 'In Use')], default='Available', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/')),
                ('qr_code_base64', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, help_text='When the asset record was created (auto-added).', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Printer', 'Printer'), ('phone', 'phone'), ('cell', 'cell')], max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('In Use', 'In Use')], default='In Use', max_length=50)),
                ('assigned_at', models.DateTimeField(blank=True, help_text='When this asset was assigned to the employee.', null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_app.asset')),
            ],
        ),
        migrations.CreateModel(
            name='ProcurementRequest1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('status', models.CharField(default='Manager Approval Pending', max_length=50)),
                ('payment_status', models.CharField(default='Unpaid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcurementRequestInitial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Server', 'Server'), ('Software License', 'Software License'), ('Peripheral', 'Peripheral')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Requirement Raised', 'Requirement Raised'), ('Purchase Approved', 'Purchase Approved'), ('Vendor Selected', 'Vendor Selected'), ('Asset Received', 'Asset Received'), ('Asset Added', 'Asset Added')], default='Requirement Raised', max_length=50)),
                ('vendor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_order_number', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('warranty_period', models.CharField(blank=True, max_length=50, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcurementRequestWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending Manager Approval', 'Pending Manager Approval'), ('Rejected by Manager', 'Rejected by Manager'), ('Pending Purchase Approval', 'Pending Purchase Approval'), ('Rejected by Purchase Manager', 'Rejected by Purchase Manager'), ('Invoice Pending', 'Invoice Pending'), ('Payment Pending', 'Payment Pending'), ('Rejected by Accounts Manager', 'Rejected by Accounts Manager'), ('Completed', 'Completed')], default='Pending Manager Approval', max_length=50)),
                ('payment_status', models.CharField(default='Unpaid', max_length=50)),
                ('vendor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_order', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_file1', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('invoice_file2', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('invoice_file3', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='asset_app.asset')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
