# Generated by Django 5.2.5 on 2026-01-03 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0002_alter_asset_created_at_alter_assignment_assigned_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='employee_name',
        ),
        migrations.AddField(
            model_name='assignment',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='asset_app.employee'),
            preserve_default=False,
        ),
    ]
