# Generated by Django 5.2.5 on 2026-01-03 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0004_rename_employee_id_employee_emp_id_employee_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emp_id',
            new_name='employee_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
