# Generated by Django 6.0.6 on 2026-09-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0005_rename_emp_id_employee_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
