# Generated by Django 6.0.6 on 2026-09-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0006_asset_cost_asset_purchase_date_asset_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('In Use', 'In Use'), ('Returned', 'Returned')], default='In Use', max_length=50),
        ),
    ]
