# Generated by Django 6.0.6 on 2026-09-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0007_alter_assignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequest',
            name='asset_category',
            field=models.CharField(default='Laptop', max_length=50),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='required_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(default='Laptop', max_length=50),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='asset_type',
            field=models.CharField(max_length=100),
        ),
    ]
