# Generated by Django 6.0.6 on 2026-09-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0008_assetrequest_asset_category_assetrequest_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
