# Generated by Django 6.0.6 on 2026-09-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0009_employee_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='agreement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
