# Generated by Django 6.1 on 2026-09-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0010_assignment_agreement_date_assignment_is_signed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('In Use', 'In Use'), ('Temporary', 'Temporary')], default='Available', max_length=50),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('In Use', 'In Use'), ('Returned', 'Returned'), ('Temporary', 'Temporary Use')], default='In Use', max_length=50),
        ),
    ]
