# Generated by Django 6.1 on 2026-09-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0011_alter_asset_status_alter_assignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
