# Generated by Django 6.1 on 2026-09-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0012_alter_asset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assigned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
