# Generated by Django 6.1 on 2026-09-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0013_assignment_assigned_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='return_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
