# Generated by Django 6.1 on 2026-09-07 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0015_returnrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementrequestworkflow',
            name='status',
            field=models.CharField(choices=[('Pending Manager Approval', 'Pending Manager Approval'), ('Rejected by Manager', 'Rejected by Manager'), ('Pending Admin Approval', 'Pending Admin Approval'), ('Rejected by Admin', 'Rejected by Admin'), ('Completed', 'Completed')], default='Pending Manager Approval', max_length=50),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('asset_request', 'Asset Request'), ('ticket', 'Ticket'), ('procurement', 'Procurement Request'), ('return_request', 'Return Request')], default='asset_request', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
