# Generated by Django 6.1 on 2026-09-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0016_alter_procurementrequestworkflow_status_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='ram',
            field=models.CharField(blank=True, choices=[('4GB', '4GB'), ('8GB', '8GB'), ('12GB', '12GB'), ('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='storage',
            field=models.CharField(blank=True, choices=[('128GB', '128GB'), ('256GB', '256GB'), ('512GB', '512GB'), ('1TB', '1TB'), ('2TB', '2TB'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='warranty',
            field=models.CharField(blank=True, choices=[('1', '1 Year'), ('2', '2 Years'), ('3', '3 Years')], max_length=10, null=True),
        ),
    ]
