# Generated by Django 6.0.6 on 2026-09-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0018_assignment_assigned_by_assethistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
