# Generated by Django 6.0.6 on 2026-09-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0020_employee_email_ticket_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='department',
            field=models.CharField(choices=[('IT Support', 'IT Support'), ('Network Support', 'Network Support'), ('Hardware Support', 'Hardware Support')], default='IT Support', max_length=50),
        ),
    ]
