# Generated by Django 6.1 on 2026-09-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0021_ticket_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='ram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(default='Available', max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='storage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='warranty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='status',
            field=models.CharField(choices=[('Pending_Manager', 'Pending Manager Approval'), ('Pending_Admin', 'Pending Admin Approval'), ('Pending_SuperAdmin', 'Pending Super Admin Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending_Manager', max_length=20),
        ),
        migrations.AlterField(
            model_name='procurementrequestworkflow',
            name='status',
            field=models.CharField(choices=[('Pending Manager Approval', 'Pending Manager Approval'), ('Rejected by Manager', 'Rejected by Manager'), ('Pending Admin Approval', 'Pending Admin Approval'), ('Rejected by Admin', 'Rejected by Admin'), ('Pending Super Admin Approval', 'Pending Super Admin Approval'), ('Rejected by Super Admin', 'Rejected by Super Admin'), ('Completed', 'Completed')], default='Pending Manager Approval', max_length=50),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Manager Approval'), ('Manager_Approved', 'Pending Admin Approval'), ('Admin_Approved', 'Pending Super Admin Approval'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='department',
            field=models.CharField(default='Network', max_length=100),
        ),
    ]
