# Generated by Django 6.0.6 on 2026-09-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0022_alter_asset_ram_alter_asset_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
