# Generated by Django 6.0.6 on 2026-09-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0024_assetdeletionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='graphic_card',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='processor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='series_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(default='In Use', max_length=50),
        ),
    ]
